addpath ../../include/;
addpath ../../source/;

% Input variables ---------------------------------------------------------
antenna = YagiAntenna;
frequency = 2.4e9;
power = 0.1;

latitude = 37.338380;
longitude = -115.924490;

elevation = 1;
angle = 0;

% Calculate coverage data -------------------------------------------------
tic;

floor = NoiseFloor(295, frequency);

tx = txsite(...
        "Antenna", antenna, ...
        "AntennaAngle", angle, ...
        "AntennaHeight", elevation, ...
        "Latitude", latitude, ...
        "Longitude", longitude, ...
        "Name", "Transmitter", ...
        "TransmitterFrequency", frequency, ...
        "TransmitterPower", power);

cv = coverage(tx, ...
        "MaxRange", 500, ...
        "Resolution", 3, ...
        "ShowLegend", true, ...
        "SignalStrengths", floor:-5, ...
        "Transparency", 0.6);  

toc;

viewer = siteviewer("Basemap","topographic");
show(tx);
plot(cv);

rmpath ../include/;