addpath ../include/;
addpath ../source/;

% Input variables ---------------------------------------------------------
antenna = YagiAntenna;
frequency = 2.4e9;

reflections = 1;
terrainMaterial = "concrete";
buildingMaterial = "concrete";

tx = txsite("Name","Transmitter", ...
            "Antenna", antenna, ...
            "Latitude", 40.745589, ...
            "Longitude", -74.024837, ...
            "AntennaHeight", 1, ...
            "TransmitterPower", 0.1, ...
            "TransmitterFrequency", 2.4e9);

rt1 = propagationModel("raytracing", ...
                        "Method", "sbr", ...
                        "MaxNumReflections", 0, ...
                        "BuildingsMaterial",buildingMaterial, ...
                        "TerrainMaterial",terrainMaterial);

rt2 = propagationModel("raytracing", ...
                        "Method", "sbr", ...
                        "MaxNumReflections", reflections, ...
                        "BuildingsMaterial",buildingMaterial, ...
                        "BuildingsMaterial",buildingMaterial, ...
                        "TerrainMaterial",terrainMaterial);

coverageData1 = coverage(tx, rt1, ...
        "SignalStrengths", -120:-5, ...
        "Transparency", 0.6, ...
        "Resolution", 3, ...
        "MaxRange", 500);

disp('Non-reflected coverage data computed');

coverageData2 = coverage(tx, rt2, ...
        "SignalStrengths", -120:-5, ...
        "Transparency", 0.6, ...
        "Resolution", 3, ...
        "MaxRange", 500);

disp('Reflected coverage data computed');

T1 = coverageData1.Data;
T2 = coverageData2.Data;

T1.Power = dBmToWatts(T1.Power);
T2.Power = dBmToWatts(T2.Power);

T2.Power = WattsTodBm(T2.Power - T1.Power);
T1.Power = WattsTodBm(T1.Power);

writetable(T2, 'coverage.txt');

viewer = siteviewer("Buildings","stevens.osm","Basemap","topographic");
show(tx);
plot(propagationData(T2));

rmpath ../source/;
rmpath ../include/;