addpath ../include/;

% Show antenna properties as figures --------------------------------------
%show(yagi); % Uncomment to see physical design
%show(exciter); % Uncomment to see exciter design
%pattern(yagi, frequency); % Uncomment to see emmision spectrum
%patternAzimuth(yagi, frequency); % Uncomment to see emmision on Azimuth
%patternElevation(yagi, frequency); % Uncomment to see emmision on Elevation

% Show power spectrum on map ----------------------------------------------
tx = txsite("Name","Transmitter", ...
    "Antenna", YagiAntenna, ...
    "Latitude", 40.745510, ...
    "Longitude", -74.025395, ...
    "AntennaHeight", 1, ...
    "TransmitterPower", 5, ...
    "TransmitterFrequency", 2.4e9);
show(tx)

coverage(tx, ...
    "SignalStrengths", -120:-5, ...
    "MaxRange", 260, ...
    "Resolution", 3, ...
    "Transparency", 0.6);

rmpath ../include/;