addpath ../../include/;
addpath ../../source/;

% Input variables ---------------------------------------------------------
frequency = 2.4e9;
antenna = UCA(frequency, 20, 9);
power = 0.1;

latitude = 40.745589;
longitude = -74.024837;

elevation = 1;
angle = 10;

reflections = 1;

terrainMaterial = "concrete";
buildingMaterial = "concrete";

tic;

tx = txsite(...
        "Antenna", antenna, ...
        "AntennaAngle", angle, ...
        "AntennaHeight", elevation, ...
        "Latitude", latitude, ...
        "Longitude", longitude, ...
        "Name", "Transmitter", ...
        "TransmitterFrequency", frequency, ...
        "TransmitterPower", power);

prop = propagationModel("raytracing", ...
    "Method", "sbr", ...
    "AngularSeparation","high", ...
    "MaxNumReflections", reflections, ...
    "TerrainMaterial",terrainMaterial, ...
    "BuildingsMaterial",buildingMaterial);

cv = coverage(tx, ...
        "MaxRange", 300, ...
        "Resolution", 3, ...
        "ShowLegend", true, ...
        "SignalStrengths", noiseFloor(295, frequency):-5, ...
        "Transparency", 0.6); 

toc;

siteviewer("Buildings","stevens.osm","Basemap","topographic");
plot(cv);

rmpath ../../include/;
rmpath ../../source/;