viewer = siteviewer("Buildings","stevens.osm","Basemap","topographic");

tx = txsite("Name","Small cell transmitter", ...
    "Antenna", helperM2412PhasedArray(tx.TransmitterFrequency), ...
    "Latitude", 40.745510, ...
    "Longitude", -74.025395, ...
    "AntennaHeight",10, ...
    "TransmitterPower",5, ...
    "TransmitterFrequency",28e9);
show(tx)

rtpm = propagationModel("raytracing", ...
    "Method","sbr", ...
    "MaxNumReflections",0, ...
    "BuildingsMaterial","perfect-reflector", ...
    "TerrainMaterial","perfect-reflector");

coverage(tx,rtpm, ...
    "SignalStrengths",-120:-5, ...
    "MaxRange",250, ...
    "Resolution",3, ...
    "Transparency",0.6);