% Variable definitions ----------------------------------------------------
frequency = 2.45e9;

exciterSpace = 25.4e-3;
exciterLength = 63.5e-3;
exciterDiameter = 25.4e-3;

directorCount = 18;

directorLength = [38.1 38.1 38.1 38.1 38.1  ...
                  38.1 38.1 38.1 38.1 38.1  ...
                  38.1 38.1 38.1 38.1 38.1  ...
                  38.1 38.1 38.1];
directorSpace = [12.2 28.6 41.3 41.3 41.3  ...
                 44.5 44.5 44.5 44.5 44.5  ...
                 47.6 44.5 47.6 47.6 47.6  ...
                 47.6 41.3 44.5];

reflectorLength = 82.3;
reflectorSpace = 15.9;

% Create exciter element and antenna --------------------------------------
exciter = design(dipoleFolded, frequency); % Auto generate dipole

% We should create a dipole manually using real dimensions. I have not been
% able to do so without getting errors

yagi = yagiUda("Exciter", design(dipoleFolded, 2.4e9), ...
    'NumDirectors', 18, ...
    "DirectorLength", directorLength.*10^-3, ...
    "DirectorSpacing", directorSpace.*10^-3, ...
    "ReflectorLength", reflectorLength*10^-3, ...
    "ReflectorSpacing", reflectorSpace*10^-3);

yagi.TiltAxis ='Z'; 
yagi.Tilt = 90; % Aligns the antenna with the ground

% Show antenna properties as figures --------------------------------------
%show(yagi); % Uncomment to see physical design
%show(exciter); % Uncomment to see exciter design
%pattern(yagi, frequency); % Uncomment to see emmision spectrum
%patternAzimuth(yagi, frequency); % Uncomment to see emmision on Azimuth
%patternElevation(yagi, frequency); % Uncomment to see emmision on Elevation

% Show power spectrum on map ----------------------------------------------

tx = txsite("Name","Transmitter", ...
    "Antenna", yagi, ...
    "Latitude", 40.745510, ...
    "Longitude", -74.025395, ...
    "AntennaHeight", 1, ...
    "TransmitterPower", 5, ...
    "TransmitterFrequency", 2.4e9);
show(tx)

coverage(tx, ...
    "SignalStrengths", -120:-5, ...
    "MaxRange", 260, ...
    "Resolution", 3, ...
    "Transparency", 0.6);