addpath ../utils/;

writelines("hello", "../data/test.txt");

m = bestAngle(4, 4, ...
    "nElements", 8, ...
    "Power", 1, ...
    "Frequency",  2.4e9, ...
    "Latitude", 40.745589, ...
    "Longitude", -74.024837, ...
    "Elevation", 2, ...
    "Inaccuracy",  "high", ...
    "Reflections",  1, ...
    "TerrainMaterial",  "perfect-reflector", ...
    "BuildingMaterial",  "perfect-reflector");

rmpath ../utils/;