function cov = reflectedCoverage(tx, options)

arguments
    tx

    options.inaccuracy (1,1) string = "high"
    options.num_reflects (1,1) int16 = 1

    options.terrain_material (1,1) string = "concrete"
    options.building_material (1,1) string = "concrete"
end

floor = noiseFloor(295, tx.TransmitterFrequency);

%% Define propagation models -----------------------------------------------

prop_0 = propagationModel("raytracing", ...
    "Method", "sbr", ...
    "AngularSeparation", options.inaccuracy, ...
    "MaxNumReflections", 0, ...
    "TerrainMaterial", options.terrain_material, ...
    "BuildingsMaterial", options.building_material);

prop_1 = propagationModel("raytracing", ...
    "Method", "sbr", ...
    "AngularSeparation",options.inaccuracy, ...
    "MaxNumReflections", options.num_reflects, ...
    "TerrainMaterial", options.terrain_material, ...
    "BuildingsMaterial", options.building_material);

%% Coverages macros --------------------------------------------------------
coverage_0 = coverage(tx, prop_0, ...
        "MaxRange", 500, ...
        "Resolution", 3, ...
        "ShowLegend", true, ...
        "SignalStrengths", floor:-5, ...
        "Transparency", 0.5);

coverage_1 = coverage(tx, prop_1, ...
        "MaxRange", 500, ...
        "Resolution", 3, ...
        "ShowLegend", true, ...
        "SignalStrengths", floor:-5, ...
        "Transparency", 0.5);

%% Create arrays of coverage data objects and parallel process -------------
table_0 = coverage_0.Data;
table_1 = coverage_1.Data;
table = table_1;

table_0.Power = dBm2watts(coverage_0.Data.Power);
table_1.Power = dBm2watts(coverage_1.Data.Power);

table.Power = real(watts2dBm(table_1.Power - table_0.Power));
table_0.Power = real(watts2dBm(coverage_0.Data.Power));
table_1.Power = real(watts2dBm(coverage_1.Data.Power));

writetable(table_0,'../data/coverage_0.txt', 'WriteVariableNames', true);
writetable(table_1,'../data/coverage_1.txt', 'WriteVariableNames', true);
writetable(table, '../data/coverage', 'WriteVariableNames', true);

cov = propagationData(table);

end